id = "cadence"
name = "Cadence Syntax Highlighting"
version = "0.0.2"
schema_version = 1
authors = [
    "Janez Podhostnik <janez.podhostnik@google.com>",
    "Bastian Mueller <bastian@turbolent.com>",
]
description = "Provides syntax highlighting for the Cadence programming language."
repository = "https://github.com/janezpodhostnik/cadence.zed"

[grammars.cadence]
repository = "https://github.com/bluesign/cadence-tree-sitter.git"
commit = "67f1b5e92159c3e3e6cf37ce6e77ec72dfaa1af8"

[language_servers.cadence]
name = "cadence"
language = "Cadence"
